github.com:
    users:
        asqarray:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: asqarray
