[workspace]
members = [
    "programs/*"
]
resolver = "2"

[patch.crates-io]
aes-gcm-siv = { path = "./vendor/aes-gcm-siv" }
ahash = { path = "./vendor/ahash" }
anchor-syn = { path = "./vendor/anchor-syn" }
blake3 = { path = "./vendor/blake3" }
borsh = { path = "./vendor/borsh" }
indexmap = { path = "./vendor/indexmap" }
jobserver = { path = "./vendor/jobserver" }
proc-macro2 = { version = "=1.0.89", path = "./vendor/proc-macro2" }
unicode-segmentation = { path = "./vendor/unicode-segmentation" }
zeroize_derive = { path = "./vendor/zeroize_derive" }

[profile.release]
overflow-checks = true
opt-level = 3
